
// english strings

#include "strings.h"

char * pStrings[] = {
 "Process %X cannot be opened",
 "Memory block cannot be read",
 "read %u from %u bytes only.\nUndefined memory will be marked with 'NOAC'",
 "to much (%u) bytes read",
 "requested memory size too big\nonly the first %u kB will be read",
 "*** error at item %u ***",
 "File\n%s\ncould not be opened",
 "File\n%s\nhas been written",
 "Written %u bytes in file\n%s\n",
 "Written %u from %u bytes in file\n%s\nonly",
 "Error writing to file\n%s",
 "process(%X) cannot be opened", 

 "Code - address: %X, size: %u (0x%X)",
 "Data - address: %X, size: %u (0x%X)",
 "Export directory - address: %X, size: %u (0x%X)",
 "Import directory - address: %X, size: %u (0x%X)",
 "Resource directory - address: %X, size: %u (0x%X)",
 "Import Address Table - address: %X, size: %u (0x%X)",
 "Module - address: %X, size: %u (0x%X)",

 "busy",
 "ready",
 "Line: %u/%u",
 "Hint",
 "text files",
 "all files",
 "Attribute",
 "Value",
 "Index",
 "Address",
 "Name",
 "Text",
 "Image base",
 "Image size",
 "Modules",
 "Memory Usage",
 "Heap",
 "Windows",
 "Size",
 "process couldn't be terminated\nWaitForSingleObject() failed [%X]",
 "process couldn't be terminated\ntime limit exceeded",
 "TerminateProcess() running",
 "no access to process",
 "Thread to terminate processes is busy",
 "Process cannot be opened/found",
 "Path",
 "State",
 "Class",
 "Style",
 "Flags",
 "Block size",
 "Handle",
 "Size(hex)",
 "%u objects",
 "%u objects < 2GB (%u kB reserve+commit, %u kB commit, %u kB access, %u kB readwrite)",
 "%u objects, %u kB used",
 "%u objects, %u kB used",
 "Memory block, address %X",
 "*.txt",
 "*.*",
 "selected: %u objects, %u kB commit+reserve, %u kB commit, %u kB readwrite",
 "I&mage",
 "&PE header",
 "&Code",
 "&Data",
 "&Exports",
 "&Imports",
 "&Resources",
 "I&AT",
 "Number",
 "Memory",
 "Memory block - address: %X, size: %u (0x%X)",
 "Unable to write to memory space of process %X", 
 "Save to disk",
 "Copy selected lines to clipboard",
 "Not enough memory to complete this function",
 "selected: %u objects occupying %u kB",
 "No more occurances found",
 "Invalid input, please enter '0'-'9' or 'A' - 'F' as hex nibbles only",
 "You must enter an even number of hex nibbles",
 "Abouttext dummy",
 "Dlls(*.dll;*.ocx)",
 "*.dll;*.ocx;",
 "selected: %u objects, %u kB (%u bytes)",
 "Code1&6",
 "&Sections",
 "raw Size",
 "Characteristics",
 "Size",
 "Relocations",
 "Relocations - address: %X, size: %u (0x%X)",
 "Are you sure?",
 "Warning",
 "Count",
 "Applications(*.exe)",
 "*.exe",
 0};
